#ifndef QEXPRESS_VERSION_H_
#define QEXPRESS_VERSION_H_

#define QEXPRESS_VERSION "0.1.0"

#define QEXPRESS_MAJOR_VERSION 0
#define QEXPRESS_MINOR_VERSION 1
#define QEXPRESS_PATCH_VERSION 0

#endif  // QEXPRESS_VERSION_H_
